language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "CasHW9yeFArEWlITeIW3xXTm+JwseCQs6PJe29/NdgJxKbub7YwrfOH36CAJMFlKF/t+eZZqlNHZFDN/kvSr2/cV7pd5kwl2rdAWbaU36NJ3GseW5sWWYV1sXlpxDiS4XnrNzhLMTBwxbxL+ZMdHql3/qW6FauPoFhyHQ3tesCuadjUXHlPH36dfujIqB+6R4wDdpfGLqQs2NOPOjYwwYolowHq0a3gkkDxBp93tZSDJRnRIdl/CVtl+5T0soFmX1mys5/b8/7wSs4fFs+Kc7lpw76Hk4oUwHpOlgCzsZN91XYvuGXrdf8S+QhmJY9HubOr7z5tHJkwc/HqOwZUZpYvYW705s3hc8Ocu4YrcmnUq9FEazYl8PZ3fREJCECqHirNN/6I/mB/OiiZktB1PQJbw7toXYMkYIDGLFeFGh2IrP0x33rCrk0KyjDqusMZRtVKDJMv9ql9EKY3f4IqSXDDqGnaV6rOIR2WPTpFUwiLBLRad5PenOEJYRMrwRyNW/+9mg5KN3WV0Dv6NdC6WSfjvKbk0qoD35U2I8Tj+YMAr//0RQr4v0f0d3YmnUIZosRhw4ToO7GlPzacq5YYDmeY2ATyVGT6C7xFLi/ThERrFz+ojCKqXx0mIj/dk4qQF/wydMaDvHxOQ8iHKKAJD/S1/Yol3LFO3mZ1LXhpn5KE="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "CasHW9yeFArEWlITeIW3xXTm+JwseCQs6PJe29/NdgJxKbub7YwrfOH36CAJMFlKF/t+eZZqlNHZFDN/kvSr2/cV7pd5kwl2rdAWbaU36NJ3GseW5sWWYV1sXlpxDiS4XnrNzhLMTBwxbxL+ZMdHql3/qW6FauPoFhyHQ3tesCuadjUXHlPH36dfujIqB+6R4wDdpfGLqQs2NOPOjYwwYolowHq0a3gkkDxBp93tZSDJRnRIdl/CVtl+5T0soFmX1mys5/b8/7wSs4fFs+Kc7lpw76Hk4oUwHpOlgCzsZN91XYvuGXrdf8S+QhmJY9HubOr7z5tHJkwc/HqOwZUZpYvYW705s3hc8Ocu4YrcmnUq9FEazYl8PZ3fREJCECqHirNN/6I/mB/OiiZktB1PQJbw7toXYMkYIDGLFeFGh2IrP0x33rCrk0KyjDqusMZRtVKDJMv9ql9EKY3f4IqSXDDqGnaV6rOIR2WPTpFUwiLBLRad5PenOEJYRMrwRyNW/+9mg5KN3WV0Dv6NdC6WSfjvKbk0qoD35U2I8Tj+YMAr//0RQr4v0f0d3YmnUIZosRhw4ToO7GlPzacq5YYDmeY2ATyVGT6C7xFLi/ThERrFz+ojCKqXx0mIj/dk4qQF/wydMaDvHxOQ8iHKKAJD/S1/Yol3LFO3mZ1LXhpn5KE="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "JwTbdpIcTYvu5nfPnCWihJbxyglPHy+gZO886OdL0kO1aBLASCEZKraFpGqIelTntJ6RINN2Nej7IYBbIUqt3ROCIOZM897QA1XBi+pVVyZBuMgJ5QTOT7zYltYNI/6y+qfW/3keKYZ2gi6F9siYJacpsNKvIl759yTPMRxxCrkcgw1RFd/+uBqRS/4FF7oj1JuYwQHUpsN1AMVnD10aQ682mJ585cbCjt5N/avWf61DLb6kdFDEf+7t0jpdOHA+zWBgQ8b628dAt7ZygZFIqPlcyxa1aICZyYXEJFKYJCZAVfdZiOyBF1R6R22T87ZhMng0pwcm44u6z1CYPsqlI0tfHch4BxtWf6tdU0fllBkDAI5t+O2AR0vc+deVtNMT2YyY8Ebwn2T/Z7v0ZUL1HV/BzUQ+4NmDNfYBG+s0X4PG6XO84J4+Gj12GzFuBcOe2HhNRhBLa2fM9+38j5B36j6QfUacl6wvBrYFHP6X5SgkVaeK2GLhOamYQqPTG0unb1j7WmHOgbjmBuznEOSLdthh9F7dfFfwRPwk0t2xj34PCiYtXAraeMb4TY+Ed97kUGn0XQOl17Dt1Yg0JnmnjM0tmlZROit1JDFcGxfBEXKuvWfgVusd86lVT3oKt1aIVPW8eW6vNa6gz3B99beBnoauzbZvpDVn2U7zgyL8H+I="
    on:
      tags: true
    skip_cleanup: true
